version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - premier-app:/usr/src/app
      - /usr/src/app/node_modules
    container_name: premier-league
    restart: always
    ports:
      - 8000:8000
      - 9229:9229
    command: npm run dev
    depends_on:
      - mongo
      # - redis
    networks:
      - premier
      
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - database_mongo:/data/db
    networks:
      - premier
  
  # redis:
  #   image: redis:alpine
  #   volumes:
  #     - /var/redis/data:/data 

volumes: 
  premier-app:
  database_mongo:

networks:
  premier: